-- ================================================================
-- Migration: Add UNIQUE constraint to slug column
-- ================================================================
-- After backfilling all existing locations with new slugs, add
-- a unique constraint to enforce slug uniqueness at the database level.
--
-- Prerequisites:
--   - All existing locations have been backfilled with unique slugs
--   - No duplicate slugs exist in the database
--
-- This constraint ensures:
--   1. No two locations can have the same slug
--   2. Database-level enforcement (beyond trigger logic)
--   3. Better query performance with unique index
-- ================================================================

-- First verify no duplicates exist (this query should return 0 rows)
-- Run this check before applying the constraint:
-- SELECT slug, COUNT(*) FROM locations WHERE slug IS NOT NULL GROUP BY slug HAVING COUNT(*) > 1;

-- Add UNIQUE constraint to slug column
-- Note: This will fail if any duplicate slugs exist
ALTER TABLE locations
  ADD CONSTRAINT locations_slug_unique UNIQUE (slug);

-- Add comment
COMMENT ON CONSTRAINT locations_slug_unique ON locations IS
  'Ensures slug uniqueness across all locations. Slugs are auto-generated by trigger_generate_location_slug().';

-- Verify the constraint was added successfully
-- SELECT conname, contype, pg_get_constraintdef(oid)
-- FROM pg_constraint
-- WHERE conrelid = 'locations'::regclass AND conname = 'locations_slug_unique';
